identifier: blackpill_f401cc
name: BlackPill F401CC
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
ram: 40
supported:
  - gpio
  - i2c
  - counter
  - spi
  - usb_device
  - lsm303dlhc
  - nvs
